[conf]
default-lang = "tur"

[lang.tur]
"Tablo" = "Tablo"
"Şekil" = "Şekil"
"TÜRKİYE CUMHURİYETİ" = "TÜRKİYE CUMHURİYETİ"
"YILDIZ TEKNİK ÜNİVERSİTESİ" = "YILDIZ TEKNİK ÜNİVERSİTESİ"
"BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ" = "BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ"
"ÖZET" = "ÖZET"
"Bilgisayar Mühendisliği Bölümü" = "Bilgisayar Mühendisliği Bölümü"
"Bilgisayar Projesi" = "Bilgisayar Projesi"
"Danışman" = "Danışman"
"copyright notice" = "Bu projenin bütün hakları Yıldız Teknik Üniversitesi Bilgisayar Mühendisliği Bölümü'ne aittir"
"TEŞEKKÜR" = "TEŞEKKÜR"
"İÇİNDEKİLER" = "İÇİNDEKİLER"
"SİMGE LİSTESİ" = "SİMGE LİSTESİ"
"KISALTMA LİSTESİ" = "KISALTMA LİSTESİ"
"ŞEKİL LİSTESİ" = "ŞEKİL LİSTESİ"
"TABLO LİSTESİ" = "TABLO LİSTESİ"
"Anahtar Kelimeler" = "Anahtar Kelimeler"
"Özgeçmiş" = "Özgeçmiş"
"İsim-Soyisim" = "İsim-Soyisim"
"Doğum Tarihi ve Yeri" = "Doğum Tarihi ve Yeri"
"Email" = "Email"
"Telefon" = "Telefon"
"Referanslar" = "Referanslar"
"Kod" = "Kod"

[lang.en]
"ÖZET" = "ABSTRACT"
"Danışman" = "Advisor"
"Anahtar Kelimeler" = "Keywords"
"Tablo" = "Table"
"Şekil" = "Figure"
"TÜRKİYE CUMHURİYETİ" = "REPUBLIC OF TÜRKİYE"
"YILDIZ TEKNİK ÜNİVERSİTESİ" = "YILDIZ TECHNICAL UNIVERSITY"
"BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ" = "COMPUTER ENGINEERING DEPARTMANT"
"Bilgisayar Mühendisliği Bölümü" = "Computer Engineering Departmant"
"Bilgisayar Projesi" = "Computer Project"
"copyright notice" = "All rights reserved to Yıldız Technical University, Computer Engineering Department"
"TEŞEKKÜR" = "ACKNOWLEDGEMENT"
"İÇİNDEKİLER" = "TABLE OF CONTENTS"
"SİMGE LİSTESİ" = "LIST OF SYMBOLS"
"KISALTMA LİSTESİ" = "LIST OF ABBREVIATIONS"
"ŞEKİL LİSTESİ" = "LIST OF FIGURES"
"TABLO LİSTESİ" = "LIST OF TABLES"
"Özgeçmiş" = "Curriculum Vitae"
"İsim-Soyisim" = "Name-Surname"
"Doğum Tarihi ve Yeri" = "Birthdate and Place of Birth"
"Email" = "Email"
"Telefon" = "Phone"
"Referanslar" = "References"
"Kod" = "Listing"
